- name: Using Zabbix collection
  hosts: localhost
  tasks:
    - name: Set connection specific variables
      set_fact:
        ansible_network_os: community.zabbix.zabbix
        ansible_connection: httpapi
        ansible_httpapi_port: 80
        ansible_httpapi_use_ssl: false
        ansible_httpapi_validate_certs: false
        ansible_zabbix_url_path: 'zabbix'  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
        ansible_user: "{{ lookup('env','ZABBIX_USER') }}"
        ansible_httpapi_pass: "{{ lookup('env','ZABBIX_PASSWORD') }}"  

    - name: Import Zabbix Training from XML
      community.zabbix.zabbix_template:
        template_xml: "{{ lookup('file', '../templates/Templates-Training-Zabbix-6.0.xml') }}"
        state: present