---
- name: Install EDU Zabbix Server with MySQL
  hosts: localhost
  become: true

  tasks:
    - name: Ensure cron is installed
      ansible.builtin.package:
        name: cron
        state: present

    - name: Upload crontab file
      ansible.builtin.copy:
        src: ../../crontab/zabbix-training
        dest: /etc/cron.d/zabbix-training
        owner: root
        group: root
        mode: '0644'

    - name: Ensure correct permissions for cron files
      ansible.builtin.file:
        path: /etc/cron.d/zabbix-training
        mode: '0644'
        owner: root
        group: root

    - name: Restart cron service
      ansible.builtin.service:
        name: cron
        state: restarted
        enabled: true

    - name: Získání aktuálního hostname
      ansible.builtin.command: /bin/hostname
      register: current_hostname

    - name: Extrakce první části hostname
      set_fact:
        new_hostname: "{{ current_hostname.stdout.split('.')[0] }}"

    - name: Nastavení nového hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Aktualizace /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1"
        line: "127.0.1.1 {{ new_hostname }}"
        state: present

#    - name: Konfigurace SSH serveru
#      ansible.posix.sshd:
#        options:
#          PermitRootLogin: "prohibit-password"
#          PasswordAuthentication: "yes"
#          ChallengeResponseAuthentication "no"

#    - name: Restart SSH
#      ansible.builtin.service:
#        name: sshd
#        state: restarted

  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_users:
          - name: zbx_monitor
            host: "localhost"
            password: ZabbixEDU_Monitoring_DB_Pass
            priv: "zbx_monitor.*:ALL"
        mysql_users:
          - name: zbx_probe
            host: "localhost"
            password: ZabbixEDU_Monitoring_ODBC_DB_Pass
            priv: "zbx_probe.*:ALL"
    - role: geerlingguy.apache
    - role: geerlingguy.php
      vars:
        php_memory_limit: "128M"
        php_max_execution_time: "300"
        php_upload_max_filesize: "256M"
    - role: community.zabbix.zabbix_agent
      vars:
        zabbix_agent_version: 7.0
        zabbix_agent2: true
        zabbix_agent_server: 127.0.0.1,enceladus.pfsense.cz
        zabbix_agent_serveractive: 127.0.0.1
        zabbix_agent_logremotecommands: "True"
        zabbix_agent_userparameters_templates_src: "templates/userparameters"
        zabbix_agent_include_dir: "/etc/zabbix/zabbix_agent2.d/"
        zabbix_agent_userparameters:
          - name: training
        zabbix_agent_host_state: present
    - role: community.zabbix.zabbix_server
      vars:
        zabbix_server_version: 7.0
        zabbix_server_database: mysql
        zabbix_server_dbname: zabbix
        zabbix_server_dbuser: zabbix
        zabbix_server_dbpassword: ZabbixEDU_DB_Pass
        zabbix_server_dbhost: localhost
        zabbix_server_repo: "zabbix-official"
        zabbix_server_cachesize: "64M"
        zabbix_server_historycachesize: "32M"
        zabbix_server_historyindexcachesize: "8M"
        zabbix_server_valuecachesize: "16M"
        zabbix_server_startpollers: "6"
        zabbix_server_startagentpollers: "3"
        zabbix_server_startpingers: "3"
        zabbix_server_startjavapollers: "1"
        zabbix_server_startipmipollers: "1"
        zabbix_server_startreportwriters: "0"
        zabbix_server_startsnmptrapper: "0"
        zabbix_server_startvmwarecollectors: "1"
        zabbix_server_javagateway: localhost
        zabbix_server_javagatewayport: "10052"
        zabbix_server_externalscripts:
         - path: "{{ lookup('first_found', '../../zabbix/externalscripts/date.sh') }}"
           name: "date.sh"
    - role: community.zabbix.zabbix_javagateway
      vars:
        zabbix_javagateway_version: 7.0
        zabbix_javagateway_listenip: localhost
        zabbix_javagateway_listenport: "10052"
        zabbix_javagateway_startpollers: "3"
    - role: community.zabbix.zabbix_web
      vars:
        zabbix_web_version: 7.0
        zabbix_server_name: "EDU Zabbix"
        zabbix_web_http_server: apache
        zabbix_timezone: Europe/Prague
        zabbix_server_hostname: localhost
        zabbix_server_database: mysql
        zabbix_server_dbname: zabbix
        zabbix_server_dbuser: zabbix
        zabbix_server_dbpassword: ZabbixEDU_DB_Pass
        zabbix_server_dbhost: localhost
        zabbix_db_type_long: mysql
        zabbix_server_dbport: 3306
...